import { useState } from 'react';
import { Droplets, Dumbbell, Footprints, Minus, Moon, Scale, Sparkles, Utensils } from 'lucide-react';
import { endpoints } from '../services/api.js';
import { Modal, ErrorBox } from './Ui.jsx';

export default function QuickAdd({open,onClose,onNavigate}){
 const [mode,setMode]=useState(null),[weight,setWeight]=useState(''),[meters,setMeters]=useState(''),[sleepHours,setSleepHours]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const reset=()=>{setMode(null);setWeight('');setMeters('');setSleepHours('');setError('');onClose()}; const run=async fn=>{setBusy(true);setError('');try{await fn();reset();window.dispatchEvent(new Event('fitcore:refresh'))}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <Modal open={open} title={mode?'Registro rápido':'¿Qué querés registrar?'} onClose={reset}>{!mode&&<div className="quick-modal-grid"><button onClick={()=>{reset();onNavigate('/nutrition?add=meal')}}><Utensils/><strong>Comida</strong><span>Manual o con IA</span></button><button onClick={()=>setMode('water')}><Droplets/><strong>Agua</strong><span>Agregar o quitar 1 L</span></button><button onClick={()=>setMode('meters')}><Footprints/><strong>Recorrido</strong><span>Metros del día</span></button><button onClick={()=>setMode('sleep')}><Moon/><strong>Sueño</strong><span>Horas dormidas</span></button><button onClick={()=>setMode('weight')}><Scale/><strong>Peso</strong><span>Nuevo registro</span></button><button onClick={()=>{reset();onNavigate('/gym')}}><Dumbbell/><strong>Gym</strong><span>Sesión completa</span></button><button onClick={()=>{reset();onNavigate('/ai')}}><Sparkles/><strong>Zhealth AI</strong><span>Preguntá o analizá</span></button></div>}
 {mode==='water'&&<div className="form-stack"><p className="muted">Cada toque suma o resta <strong>1 litro</strong>. Tu meta diaria se configura desde tu perfil.</p><div className="simple-counter-actions"><button className="counter-minus" disabled={busy} onClick={()=>run(()=>endpoints.subtractWater(1))}><Minus/> Quitar 1 L</button><button className="counter-plus" disabled={busy} onClick={()=>run(()=>endpoints.addWater(1))}>+ Agregar 1 L</button></div><ErrorBox message={error}/></div>}
 {mode==='meters'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();run(()=>endpoints.addActivity({meters:Number(meters)}))}}><label>Metros recorridos hoy<input autoFocus type="number" min="0" value={meters} onChange={e=>setMeters(e.target.value)} placeholder="Ingrese los metros recorridos" required/></label><ErrorBox message={error}/><button className="btn primary" disabled={busy||meters===''}>Guardar recorrido</button></form>}
 {mode==='sleep'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();run(()=>endpoints.addSleep({hours:Number(sleepHours)}))}}><label>Horas dormidas<input autoFocus type="number" min="0" max="24" step="0.25" value={sleepHours} onChange={e=>setSleepHours(e.target.value)} placeholder="Ingrese cuántas horas durmió" required/></label><ErrorBox message={error}/><button className="btn primary" disabled={busy||!sleepHours}>Guardar sueño</button></form>}
 {mode==='weight'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();run(()=>endpoints.addWeight({weightLb:Number(weight)}))}}><label>Peso actual (lb)<input autoFocus type="number" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="Ingrese su peso actual" required/></label><ErrorBox message={error}/><button className="btn primary" disabled={busy||!weight}>Guardar peso</button></form>}</Modal>;
}
