import { useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Eye, EyeOff, KeyRound, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { endpoints } from '../services/api.js';
import { ErrorBox } from '../components/Ui.jsx';
import { useNavigate } from 'react-router-dom';

const initial={name:'',username:'',email:'',password:''};
export default function AuthPage(){
 const [mode,setMode]=useState('login'),[show,setShow]=useState(false),[form,setForm]=useState(initial),[reset,setReset]=useState({email:'',code:'',password:''}),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const {login,register}=useAuth(); const nav=useNavigate(); const set=k=>e=>setForm(v=>({...v,[k]:e.target.value})); const switchMode=n=>{setMode(n);setError('');setNotice('')};
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='login'){await login({email:form.email,password:form.password});nav('/')}else{await register(form);nav('/onboarding')}}catch(err){setError(err.message)}finally{setBusy(false)}};
 const requestCode=async e=>{e.preventDefault();setBusy(true);setError('');try{await endpoints.forgotPassword(reset.email);setNotice('Si existe una cuenta con ese correo, enviamos un código de 6 dígitos.');setMode('reset')}catch(err){setError(err.message)}finally{setBusy(false)}};
 const doReset=async e=>{e.preventDefault();setBusy(true);setError('');try{await endpoints.resetPassword(reset.email,reset.code,reset.password);setNotice('Contraseña actualizada. Ya podés iniciar sesión.');setForm(v=>({...v,email:reset.email,password:''}));setMode('login')}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div className="auth-page"><div className="auth-hero"><div className="auth-brand auth-brand-logo"><img src="/zhealth-logo.png" alt="Zhealth"/></div><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> Tu progreso, conectado</span><h1>Construí consistencia.<br/><em>Medí el progreso.</em></h1><p>Nutrición, actividad, descanso y un plan adaptado a tus objetivos.</p></div><div className="hero-orbit"><Activity/></div></div><div className="auth-panel">
 {['login','register'].includes(mode)&&<div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>switchMode('login')}>Entrar</button><button className={mode==='register'?'active':''} onClick={()=>switchMode('register')}>Crear cuenta</button></div>}
 {mode==='forgot'&&<form onSubmit={requestCode} className="auth-form"><button type="button" className="text-btn back-link" onClick={()=>switchMode('login')}><ArrowLeft size={16}/> Volver</button><div><span className="eyebrow">Recuperación</span><h2>Restablecé tu contraseña</h2><p className="muted">Te enviaremos un código temporal al correo de tu cuenta.</p></div><label>Correo<input type="email" value={reset.email} onChange={e=>setReset({...reset,email:e.target.value})} placeholder="Ingrese el correo de su cuenta" required/></label><ErrorBox message={error}/>{notice&&<p className="success-text">{notice}</p>}<button className="btn primary large" disabled={busy}><KeyRound size={18}/>{busy?'Enviando...':'Enviar código'}</button></form>}
 {mode==='reset'&&<form onSubmit={doReset} className="auth-form"><button type="button" className="text-btn back-link" onClick={()=>switchMode('forgot')}><ArrowLeft size={16}/> Volver</button><div><span className="eyebrow">Código enviado</span><h2>Creá una nueva contraseña</h2><p className="muted">El código vence en 15 minutos.</p></div><label>Código de 6 dígitos<input inputMode="numeric" maxLength="6" value={reset.code} onChange={e=>setReset({...reset,code:e.target.value.replace(/\D/g,'')})} placeholder="Ingrese el código recibido" required/></label><label>Nueva contraseña<input type="password" minLength="8" value={reset.password} onChange={e=>setReset({...reset,password:e.target.value})} placeholder="Ingrese su nueva contraseña" required/></label><ErrorBox message={error}/><button className="btn primary large" disabled={busy}>{busy?'Guardando...':'Cambiar contraseña'}<ArrowRight size={18}/></button></form>}
 {['login','register'].includes(mode)&&<form onSubmit={submit} className="auth-form"><div><span className="eyebrow">{mode==='login'?'Bienvenido de nuevo':'Paso 1 de 2'}</span><h2>{mode==='login'?'Entrá a tu cuenta':'Creá tu cuenta'}</h2>{mode==='register'&&<p className="muted">Primero creamos tu cuenta. En la siguiente pantalla configurás tus objetivos y métricas.</p>}</div>{mode==='register'&&<div className="form-row"><label>Nombre<input value={form.name} onChange={set('name')} placeholder="Ingrese su nombre" required/></label><label>Nombre de usuario<input value={form.username} onChange={set('username')} placeholder="Ingrese su nombre de usuario" required/></label></div>}<label>Correo<input type="email" value={form.email} onChange={set('email')} placeholder="Ingrese su correo electrónico" required/></label><label>Contraseña<div className="password-field"><input type={show?'text':'password'} value={form.password} onChange={set('password')} placeholder="Ingrese una contraseña de mínimo 8 caracteres" minLength="8" required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{mode==='login'&&<button type="button" className="text-btn forgot-link" onClick={()=>{setReset(v=>({...v,email:form.email}));switchMode('forgot')}}>¿Olvidaste tu contraseña?</button>}<ErrorBox message={error}/><button className="btn primary large" disabled={busy}>{busy?'Procesando...':mode==='login'?'Entrar':'Continuar con mi perfil'}<ArrowRight size={18}/></button></form>}
 </div></div>;
}
