import { useEffect, useState } from 'react';
import { BarChart3, Dumbbell, Plus, Trash2, TrendingUp } from 'lucide-react';
import { endpoints } from '../services/api.js';
import { Card, Empty, ErrorBox, Loading, Pill, SectionTitle, SuccessAlert } from '../components/Ui.jsx';
import Sparkline from '../components/Sparkline.jsx';
import { n, shortDate } from '../utils/format.js';

const emptyExercise=()=>({name:'',sets:'',reps:'',weightLb:''});
const typeLabels={upper:'Torso',lower:'Pierna',push:'Push',pull:'Pull',legs:'Pierna',full_body:'Cuerpo completo',cardio:'Cardio',other:'Otro'};
export default function GymPage(){
 const [week,setWeek]=useState(null),[history,setHistory]=useState([]),[progress,setProgress]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false);
 const [form,setForm]=useState({title:'',workoutType:'',durationMinutes:'',perceivedEffort:'',notes:'',exercises:[emptyExercise()]});
 const load=async()=>{try{const [w,h,p]=await Promise.all([endpoints.gym(),endpoints.gymHistory(),endpoints.gymProgress()]);setWeek(w);setHistory(h);setProgress(p)}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]); if(!week)return <Loading/>;
 const updateExercise=(i,k,v)=>setForm(f=>({...f,exercises:f.exercises.map((x,j)=>j===i?{...x,[k]:v}:x)})); const addExercise=()=>setForm(f=>({...f,exercises:[...f.exercises,emptyExercise()]})); const removeExercise=i=>setForm(f=>({...f,exercises:f.exercises.filter((_,j)=>j!==i)}));
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await endpoints.addGym({...form,durationMinutes:Number(form.durationMinutes)||0,perceivedEffort:form.perceivedEffort?Number(form.perceivedEffort):undefined,exercises:form.exercises.filter(x=>x.name.trim()).map(x=>({...x,sets:Number(x.sets)||1,reps:Number(x.reps)||1,weightLb:Number(x.weightLb)||0}))});setForm({title:'',workoutType:'',durationMinutes:'',perceivedEffort:'',notes:'',exercises:[emptyExercise()]});await load();window.dispatchEvent(new Event('fitcore:refresh'));setSuccess(true)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const volumeValues=progress?.weeks?.map(x=>x.volumeLb)||[];
 return <div className="page gym-page"><div className="page-heading"><div><span className="eyebrow">Gym</span><h1>Entrená y mirá tu progreso.</h1><p className="muted">Guardá sesiones, ejercicios, cargas y volumen para comparar tu avance.</p></div><Pill tone="green">{week.completed}/{week.goal} esta semana</Pill></div><ErrorBox message={error}/>
 <div className="gym-summary-grid"><Card><span>Sesiones</span><strong>{week.completed}</strong><small>Meta semanal: {week.goal}</small></Card><Card><span>Tiempo</span><strong>{n(week.totalMinutes)} min</strong><small>Esta semana</small></Card><Card><span>Volumen</span><strong>{n(week.totalVolumeLb)} lb</strong><small>Series × reps × carga</small></Card></div>
 <Card><SectionTitle title="Registrar entrenamiento" action={<Dumbbell size={18}/>}/><form className="form-stack" onSubmit={submit}><div className="form-row"><label>Nombre de la sesión<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ingrese un nombre para el entrenamiento" required/></label><label>Tipo<select value={form.workoutType} onChange={e=>setForm({...form,workoutType:e.target.value})} required><option value="" disabled>Seleccione el tipo</option>{Object.entries(typeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="form-row"><label>Duración (min)<input type="number" min="0" max="600" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})} placeholder="Ingrese la duración del entrenamiento"/></label><label>Esfuerzo percibido<select value={form.perceivedEffort} onChange={e=>setForm({...form,perceivedEffort:e.target.value})}><option value="">Opcional</option>{Array.from({length:10},(_,i)=><option value={i+1} key={i+1}>{i+1}/10</option>)}</select></label></div><div className="exercise-builder"><div className="ingredient-head"><strong>Ejercicios</strong><button type="button" className="mini-add" onClick={addExercise}><Plus size={15}/></button></div>{form.exercises.map((ex,i)=><div className="exercise-entry" key={i}><div className="exercise-name-row"><input value={ex.name} onChange={e=>updateExercise(i,'name',e.target.value)} placeholder="Ingrese el nombre del ejercicio"/><button type="button" onClick={()=>removeExercise(i)} disabled={form.exercises.length===1}><Trash2 size={15}/></button></div><div className="exercise-fields"><label>Series<input type="number" min="1" value={ex.sets} onChange={e=>updateExercise(i,'sets',e.target.value)} placeholder="Series"/></label><label>Reps<input type="number" min="1" value={ex.reps} onChange={e=>updateExercise(i,'reps',e.target.value)} placeholder="Repeticiones"/></label><label>Peso (lb)<input type="number" min="0" step="0.5" value={ex.weightLb} onChange={e=>updateExercise(i,'weightLb',e.target.value)} placeholder="Carga usada"/></label></div></div>)}</div><label>Notas<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Agregue una nota sobre su entrenamiento si lo desea"/></label><button className="btn primary" disabled={busy}>{busy?'Guardando...':'Guardar entrenamiento'}</button></form></Card>
 <Card><SectionTitle title="Progreso de volumen" action={<TrendingUp size={18}/>}/>{volumeValues.length?<><Sparkline values={volumeValues}/><div className="gym-week-list">{progress.weeks.slice(-6).reverse().map(w=><div key={w.week}><span>{shortDate(w.week)}</span><strong>{n(w.workouts)} sesiones</strong><small>{n(w.volumeLb)} lb de volumen</small></div>)}</div></>:<Empty icon={BarChart3} title="Todavía no hay tendencia" text="Registrá varias sesiones para comenzar a ver tu progreso."/>}</Card>
 <Card><SectionTitle title="Mejores cargas por ejercicio"/>{progress?.exercises?.length?<div className="compact-list gym-exercise-progress">{progress.exercises.map(e=><div key={e.name}><div><strong>{e.name}</strong><span>{e.sessions} sesiones registradas</span></div><Pill tone="purple">{n(e.bestWeightLb,1)} lb</Pill></div>)}</div>:<p className="muted">Tus mejores cargas aparecerán aquí cuando registres ejercicios.</p>}</Card>
 <Card><SectionTitle title="Historial reciente"/>{history.length?<div className="gym-history-list">{history.map(log=><div className="gym-history-item" key={log._id}><div><strong>{log.title}</strong><span>{typeLabels[log.workoutType]||'Entrenamiento'} · {shortDate(log.completedAt)}</span></div><div><b>{log.exercises?.length||0}</b><small>ejercicios</small></div><div><b>{n(log.durationMinutes)}</b><small>min</small></div></div>)}</div>:<Empty icon={Dumbbell} title="Sin entrenamientos" text="Registrá tu primera sesión para comenzar el historial."/>}</Card>
 <SuccessAlert open={success} title="Entrenamiento guardado" text="Tu sesión y su progreso ya forman parte de tu historial." onClose={()=>setSuccess(false)}/></div>;
}
