import { useState } from 'react';
import { ArrowRight, HeartPulse, Target } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { endpoints } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';
import { Card, ErrorBox } from '../components/Ui.jsx';

export default function OnboardingPage(){
 const {user,refreshUser}=useAuth(); const nav=useNavigate();
 const [form,setForm]=useState({birthDate:'',biologicalSex:'unspecified',heightCm:'',currentWeightLb:'',targetWeightLb:'',goal:'',activityLevel:'',waterGoalLiters:'',weeklyGymGoal:'',dailyDistanceGoalKm:'',sleepGoalHours:''});
 const [error,setError]=useState(''),[busy,setBusy]=useState(false); const set=k=>e=>setForm(v=>({...v,[k]:e.target.value}));
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await endpoints.updateMe({...form,heightCm:Number(form.heightCm),currentWeightLb:Number(form.currentWeightLb),targetWeightLb:form.targetWeightLb?Number(form.targetWeightLb):undefined,waterGoalLiters:Number(form.waterGoalLiters),weeklyGymGoal:Number(form.weeklyGymGoal),dailyDistanceGoalMeters:Number(form.dailyDistanceGoalKm)*1000,sleepGoalHours:Number(form.sleepGoalHours),onboardingCompleted:true});await endpoints.recalculatePlan(true).catch(()=>null);await refreshUser();nav('/')}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div className="onboarding-page"><div className="onboarding-wrap"><div className="onboarding-brand"><img className="onboarding-logo-mark" src="/zhealth-mark.png" alt="Zhealth"/><div><span className="eyebrow">Paso 2 de 2</span><h1>Personalicemos Zhealth para vos.</h1><p className="muted">Hola {user?.name?.split(' ')[0]}. Estos datos permiten ajustar tu plan y tus metas. Podés modificarlos después.</p></div></div><form onSubmit={submit} className="onboarding-form">
 <Card><div className="onboarding-section-title"><HeartPulse/><div><h2>Tu punto de partida</h2><span>Información para calcular tu progreso</span></div></div><div className="settings-grid"><label>Fecha de nacimiento<input type="date" value={form.birthDate} onChange={set('birthDate')} required/></label><label>Sexo para estimación<select value={form.biologicalSex} onChange={set('biologicalSex')}><option value="unspecified">Prefiero no indicar</option><option value="male">Masculino</option><option value="female">Femenino</option></select></label><label>Altura (cm)<input type="number" min="50" max="260" value={form.heightCm} onChange={set('heightCm')} placeholder="Ingrese su altura en centímetros" required/></label><label>Peso actual (lb)<input type="number" min="44" step="0.1" value={form.currentWeightLb} onChange={set('currentWeightLb')} placeholder="Ingrese su peso actual" required/></label><label>Peso objetivo (lb)<input type="number" min="44" step="0.1" value={form.targetWeightLb} onChange={set('targetWeightLb')} placeholder="Ingrese el peso que desea alcanzar"/></label><label>Actividad física<select value={form.activityLevel} onChange={set('activityLevel')} required><option value="" disabled>Seleccione su nivel de actividad</option><option value="sedentary">Sedentario · poca actividad</option><option value="light">Ligero · 1 a 3 días activos</option><option value="moderate">Moderado · 3 a 5 días activos</option><option value="active">Activo · 6 a 7 días activos</option><option value="very_active">Muy activo · actividad intensa frecuente</option></select></label></div></Card>
 <Card><div className="onboarding-section-title"><Target/><div><h2>¿Qué querés lograr?</h2><span>Zhealth adaptará el plan a tu objetivo</span></div></div><div className="settings-grid"><label>Objetivo<select value={form.goal} onChange={set('goal')} required><option value="" disabled>Seleccione su objetivo</option><option value="gain">Ganar peso</option><option value="lose">Perder grasa</option><option value="maintain">Mantener peso</option><option value="recomp">Recomposición corporal</option><option value="tracking">Solo seguimiento</option></select></label><label>Meta diaria de agua (L)<input type="number" min="0" max="15" step="0.25" value={form.waterGoalLiters} onChange={set('waterGoalLiters')} placeholder="Ingrese su meta diaria de agua" required/></label><label>Días de gym por semana<select value={form.weeklyGymGoal} onChange={set('weeklyGymGoal')} required><option value="" disabled>Seleccione cuántos días entrena</option>{Array.from({length:8},(_,i)=><option key={i} value={i}>{i} {i===1?'día':'días'}</option>)}</select></label><label>Meta diaria de recorrido (km)<input type="number" min="0" step="0.1" value={form.dailyDistanceGoalKm} onChange={set('dailyDistanceGoalKm')} placeholder="Ingrese su meta diaria en kilómetros" required/></label><label>Meta de sueño (horas)<input type="number" min="0" max="24" step="0.25" value={form.sleepGoalHours} onChange={set('sleepGoalHours')} placeholder="Ingrese sus horas objetivo de sueño" required/></label></div></Card>
 <ErrorBox message={error}/><button className="btn primary large onboarding-submit" disabled={busy}>{busy?'Creando tu plan...':'Finalizar configuración'}<ArrowRight size={18}/></button></form></div></div>;
}
