import { useEffect, useState } from 'react';
import { ChevronDown, ChevronUp, LogOut, RefreshCw, Save, Settings2, ShieldCheck, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { endpoints } from '../services/api.js';
import { Card, ErrorBox, Loading, Pill, SectionTitle, SuccessAlert } from '../components/Ui.jsx';
import { goalLabel } from '../utils/format.js';
import { AVATARS, avatarUrl } from '../utils/avatar.js';
import { useNavigate } from 'react-router-dom';

export default function ProfilePage(){
 const {user,logout,refreshUser}=useAuth();const nav=useNavigate();const [form,setForm]=useState(null),[bmi,setBmi]=useState(null),[plan,setPlan]=useState(null),[error,setError]=useState(''),[planBusy,setPlanBusy]=useState(false),[goalsOpen,setGoalsOpen]=useState(false),[success,setSuccess]=useState(false),[avatarBusy,setAvatarBusy]=useState(false);
 useEffect(()=>{setForm({name:user.name,birthDate:user.birthDate?.slice(0,10)||'',biologicalSex:user.biologicalSex||'unspecified',heightCm:user.heightCm||'',currentWeightLb:user.currentWeightLb||'',targetWeightLb:user.targetWeightLb||'',goal:user.goal||'tracking',activityLevel:user.activityLevel||'moderate',waterGoalLiters:user.waterGoalLiters??'',weeklyGymGoal:user.weeklyGymGoal??0,dailyDistanceGoalMeters:user.dailyDistanceGoalMeters??'',sleepGoalHours:user.sleepGoalHours??'',macroGoals:user.macroGoals||{calories:'',protein:'',carbs:'',fats:''}});endpoints.bmi().then(setBmi).catch(()=>{});endpoints.personalPlan().then(setPlan).catch(()=>{})},[user]);if(!form)return <Loading/>;
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const save=async e=>{e.preventDefault();setError('');try{await endpoints.updateMe({...form,heightCm:Number(form.heightCm)||undefined,currentWeightLb:form.currentWeightLb?Number(form.currentWeightLb):undefined,targetWeightLb:form.targetWeightLb?Number(form.targetWeightLb):undefined,waterGoalLiters:Number(form.waterGoalLiters)||0,weeklyGymGoal:Number(form.weeklyGymGoal),dailyDistanceGoalMeters:Number(form.dailyDistanceGoalMeters)||0,sleepGoalHours:Number(form.sleepGoalHours)||0,macroGoals:Object.fromEntries(Object.entries(form.macroGoals).map(([k,v])=>[k,Number(v)||0]))});await refreshUser();setBmi(await endpoints.bmi().catch(()=>null));setSuccess(true)}catch(e){setError(e.message)}};
 const chooseAvatar=async id=>{if(avatarBusy||Number(user.avatarId)===id)return;setAvatarBusy(true);setError('');try{await endpoints.updateMe({avatarId:id});await refreshUser()}catch(e){setError(e.message)}finally{setAvatarBusy(false)}};
 const recalc=async()=>{setPlanBusy(true);setError('');try{const data=await endpoints.recalculatePlan(true);setPlan(data.plan);await refreshUser();setSuccess(true)}catch(e){setError(e.message)}finally{setPlanBusy(false)}};
 return <div className="page"><div className="profile-head"><div className="profile-avatar avatar-image"><img src={avatarUrl(user.avatarId)} alt="Avatar"/></div><div><span className="eyebrow">@{user.username}</span><h1>{user.name}</h1><p>{goalLabel[user.goal]} · Nivel {user.level||1}</p></div><Pill tone="green">{user.xp||0} XP</Pill></div><div className="profile-quick"><Card><span>IMC</span><strong>{bmi?.bmi||'—'}</strong><small>{bmi?`${bmi.weightLb} lb / ${bmi.heightCm} cm`:'Completá altura y peso'}</small></Card><Card onClick={()=>nav('/settings')} className="clickable"><Settings2/><strong>Configuración y cuenta</strong><small>Privacidad, seguridad y preferencias</small></Card></div>
 {plan&&<Card className="plan-card"><SectionTitle title="Tu plan Zhealth" action={<Sparkles size={18}/>}/><div className="plan-main"><div><span>Calorías</span><strong>{plan.calories}</strong><small>kcal/día</small></div><div><span>Proteína</span><strong>{plan.protein}g</strong></div><div><span>Carbos</span><strong>{plan.carbs}g</strong></div><div><span>Grasas</span><strong>{plan.fats}g</strong></div></div><p className="muted">Gasto estimado: {plan.estimatedTdee} kcal · Cambio estimado: {plan.estimatedWeeklyChangeLb>0?'+':''}{plan.estimatedWeeklyChangeLb} lb/semana.</p><button className="btn secondary" onClick={recalc} disabled={planBusy}><RefreshCw size={17}/>{planBusy?'Calculando...':'Recalcular con mis datos actuales'}</button></Card>}
 <Card><SectionTitle title="Tu avatar"/><p className="muted avatar-help">El avatar se guarda en el momento en que lo seleccionás.</p><div className="avatar-picker">{AVATARS.map(a=><button type="button" key={a.id} disabled={avatarBusy} className={Number(user.avatarId)===a.id?'avatar-option selected':'avatar-option'} onClick={()=>chooseAvatar(a.id)}><img src={a.url} alt={`Avatar ${a.id}`}/></button>)}</div></Card>
 <form onSubmit={save}><Card><SectionTitle title="Perfil y objetivo"/><div className="settings-grid"><label>Nombre<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Ingrese su nombre"/></label><label>Fecha de nacimiento<input type="date" value={form.birthDate} onChange={e=>set('birthDate',e.target.value)}/></label><label>Sexo para estimación<select value={form.biologicalSex} onChange={e=>set('biologicalSex',e.target.value)}><option value="unspecified">Prefiero no indicar</option><option value="male">Masculino</option><option value="female">Femenino</option></select></label><label>Altura (cm)<input type="number" value={form.heightCm} onChange={e=>set('heightCm',e.target.value)} placeholder="Ingrese su altura"/></label><label>Peso actual (lb)<input type="number" step="0.1" value={form.currentWeightLb} onChange={e=>set('currentWeightLb',e.target.value)} placeholder="Ingrese su peso actual"/></label><label>Peso objetivo (lb)<input type="number" step="0.1" value={form.targetWeightLb} onChange={e=>set('targetWeightLb',e.target.value)} placeholder="Ingrese su peso objetivo"/></label><label>Objetivo<select value={form.goal} onChange={e=>set('goal',e.target.value)}>{Object.entries(goalLabel).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Actividad física<select value={form.activityLevel} onChange={e=>set('activityLevel',e.target.value)}><option value="sedentary">Sedentario</option><option value="light">Ligero</option><option value="moderate">Moderado</option><option value="active">Activo</option><option value="very_active">Muy activo</option></select></label></div></Card>
 <Card className="collapsible-card"><button type="button" className="collapse-trigger" onClick={()=>setGoalsOpen(v=>!v)}><div><span className="eyebrow">Metas diarias</span><strong>Editar mis objetivos del día</strong><small>Macros, agua, recorrido, sueño y gym</small></div>{goalsOpen?<ChevronUp/>:<ChevronDown/>}</button>{goalsOpen&&<div className="collapse-content"><p className="muted">Estos valores son tuyos. Podés usar el plan automático o ajustarlos manualmente.</p><div className="settings-grid"><label>Calorías<input type="number" value={form.macroGoals.calories} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,calories:e.target.value}})} placeholder="Ingrese su meta de calorías"/></label><label>Proteína (g)<input type="number" value={form.macroGoals.protein} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,protein:e.target.value}})} placeholder="Ingrese su meta de proteína"/></label><label>Carbohidratos (g)<input type="number" value={form.macroGoals.carbs} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,carbs:e.target.value}})} placeholder="Ingrese su meta de carbohidratos"/></label><label>Grasas (g)<input type="number" value={form.macroGoals.fats} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,fats:e.target.value}})} placeholder="Ingrese su meta de grasas"/></label><label>Agua (L)<input type="number" step="0.25" value={form.waterGoalLiters} onChange={e=>set('waterGoalLiters',e.target.value)} placeholder="Ingrese su meta diaria de agua"/></label><label>Gym por semana<select value={form.weeklyGymGoal} onChange={e=>set('weeklyGymGoal',e.target.value)}>{Array.from({length:8},(_,i)=><option value={i} key={i}>{i} {i===1?'día':'días'}</option>)}</select></label><label>Recorrido diario (m)<input type="number" step="100" value={form.dailyDistanceGoalMeters} onChange={e=>set('dailyDistanceGoalMeters',e.target.value)} placeholder="Ingrese su meta diaria en metros"/></label><label>Sueño objetivo (h)<input type="number" step="0.25" value={form.sleepGoalHours} onChange={e=>set('sleepGoalHours',e.target.value)} placeholder="Ingrese sus horas objetivo de sueño"/></label></div></div>}</Card><ErrorBox message={error}/><button className="btn primary profile-save"><Save size={18}/>Guardar cambios</button></form>
 <Card className="account-card"><SectionTitle title="Cuenta" action={<ShieldCheck size={18}/>}/><p className="muted">La administración de seguridad y privacidad ahora está dentro de Configuración.</p><div className="account-actions"><button className="btn secondary" onClick={()=>nav('/settings')}><Settings2 size={17}/> Abrir configuración</button><button className="btn danger-outline" onClick={()=>{logout();nav('/auth')}}><LogOut size={18}/> Cerrar sesión</button></div></Card><SuccessAlert open={success} title="Cambios guardados" text="Tus datos y metas se actualizaron correctamente." onClose={()=>setSuccess(false)}/></div>;
}
