import { useEffect, useState } from 'react';
import { LogOut, RefreshCw, Save, Settings2, ShieldCheck, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { endpoints } from '../services/api.js';
import { Card, ErrorBox, Loading, Pill, SectionTitle } from '../components/Ui.jsx';
import { goalLabel } from '../utils/format.js';
import { AVATARS, avatarUrl } from '../utils/avatar.js';
import { useNavigate } from 'react-router-dom';

export default function ProfilePage(){
 const {user,logout,refreshUser}=useAuth();
 const nav=useNavigate();
 const [form,setForm]=useState(null),[bmi,setBmi]=useState(null),[plan,setPlan]=useState(null),[error,setError]=useState(''),[saved,setSaved]=useState(false),[planBusy,setPlanBusy]=useState(false);
 useEffect(()=>{
  setForm({name:user.name,birthDate:user.birthDate?.slice(0,10)||'',biologicalSex:user.biologicalSex||'unspecified',heightCm:user.heightCm||'',startingWeightLb:user.startingWeightLb||'',currentWeightLb:user.currentWeightLb||'',targetWeightLb:user.targetWeightLb||'',avatarId:user.avatarId||1,goal:user.goal||'tracking',activityLevel:user.activityLevel||'moderate',waterGoalLiters:user.waterGoalLiters||2.5,bottleSizeLiters:user.bottleSizeLiters||1,weeklyGymGoal:user.weeklyGymGoal||3,dailyStepGoal:user.dailyStepGoal||10000,sleepGoalHours:user.sleepGoalHours||8,macroGoals:user.macroGoals||{calories:2000,protein:120,carbs:250,fats:70}});
  endpoints.bmi().then(setBmi).catch(()=>{}); endpoints.personalPlan().then(setPlan).catch(()=>{});
 },[user]);
 if(!form)return <Loading/>;
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const save=async(e)=>{e.preventDefault();setError('');try{await endpoints.updateMe({...form,heightCm:Number(form.heightCm)||undefined,startingWeightLb:Number(form.startingWeightLb)||undefined,currentWeightLb:Number(form.currentWeightLb)||undefined,targetWeightLb:Number(form.targetWeightLb)||undefined,avatarId:Number(form.avatarId),waterGoalLiters:Number(form.waterGoalLiters),bottleSizeLiters:Number(form.bottleSizeLiters),weeklyGymGoal:Number(form.weeklyGymGoal),dailyStepGoal:Number(form.dailyStepGoal),sleepGoalHours:Number(form.sleepGoalHours),macroGoals:Object.fromEntries(Object.entries(form.macroGoals).map(([k,v])=>[k,Number(v)]))});await refreshUser();setBmi(await endpoints.bmi().catch(()=>null));setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e){setError(e.message)}};
 const recalc=async()=>{setPlanBusy(true);setError('');try{const data=await endpoints.recalculatePlan(true);setPlan(data.plan);await refreshUser()}catch(e){setError(e.message)}finally{setPlanBusy(false)}};
 return <div className="page"><div className="profile-head"><div className="profile-avatar avatar-image"><img src={avatarUrl(user.avatarId)} alt="Avatar"/></div><div><span className="eyebrow">@{user.username}</span><h1>{user.name}</h1><p>{goalLabel[user.goal]} · Nivel {user.level||1}</p></div><Pill tone="green">{user.xp||0} XP</Pill></div>
 <div className="profile-quick"><Card><span>IMC</span><strong>{bmi?.bmi||'—'}</strong><small>{bmi?`${bmi.weightLb} lb / ${bmi.heightCm} cm`:'Completá altura y peso'}</small></Card><Card onClick={()=>nav('/settings')} className="clickable"><Settings2/><strong>Configuración</strong><small>Privacidad y cuenta</small></Card></div>
 {plan&&<Card className="plan-card"><SectionTitle title="Tu plan Zhealth" action={<Sparkles size={18}/>}/><div className="plan-main"><div><span>Calorías</span><strong>{plan.calories}</strong><small>kcal/día</small></div><div><span>Proteína</span><strong>{plan.protein}g</strong></div><div><span>Carbos</span><strong>{plan.carbs}g</strong></div><div><span>Grasas</span><strong>{plan.fats}g</strong></div></div><p className="muted">Gasto estimado: {plan.estimatedTdee} kcal · Cambio estimado: {plan.estimatedWeeklyChangeLb>0?'+':''}{plan.estimatedWeeklyChangeLb} lb/semana.{plan.estimatedWeeksToTarget?` Aproximadamente ${plan.estimatedWeeksToTarget} semanas hacia tu peso objetivo si la tendencia se mantiene.`:''}</p><button className="btn secondary" onClick={recalc} disabled={planBusy}><RefreshCw size={17}/>{planBusy?'Calculando...':'Recalcular con mis datos actuales'}</button></Card>}
 <form onSubmit={save}>
 <Card><SectionTitle title="Tu avatar"/><p className="muted avatar-help">Elegí uno de los cinco avatares Clay de Zhealth.</p><div className="avatar-picker">{AVATARS.map(a=><button type="button" key={a.id} className={Number(form.avatarId)===a.id?'avatar-option selected':'avatar-option'} onClick={()=>set('avatarId',a.id)}><img src={a.url} alt={`Avatar ${a.id}`}/></button>)}</div></Card>
 <Card><SectionTitle title="Perfil y objetivo"/><div className="settings-grid"><label>Nombre<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Fecha de nacimiento<input type="date" value={form.birthDate} onChange={e=>set('birthDate',e.target.value)}/></label><label>Sexo para estimación<select value={form.biologicalSex} onChange={e=>set('biologicalSex',e.target.value)}><option value="unspecified">Prefiero no indicar</option><option value="male">Masculino</option><option value="female">Femenino</option></select></label><label>Altura (cm)<input type="number" value={form.heightCm} onChange={e=>set('heightCm',e.target.value)}/></label><label>Peso actual (lb)<input type="number" step="0.1" value={form.currentWeightLb} onChange={e=>set('currentWeightLb',e.target.value)} placeholder="135"/></label><label>Peso objetivo (lb)<input type="number" step="0.1" value={form.targetWeightLb} onChange={e=>set('targetWeightLb',e.target.value)}/></label><label>Objetivo<select value={form.goal} onChange={e=>set('goal',e.target.value)}>{Object.entries(goalLabel).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Actividad<select value={form.activityLevel} onChange={e=>set('activityLevel',e.target.value)}><option value="sedentary">Sedentario</option><option value="light">Ligero</option><option value="moderate">Moderado</option><option value="active">Activo</option><option value="very_active">Muy activo</option></select></label></div></Card>
 <Card><SectionTitle title="Metas diarias"/><p className="muted">Podés usar el plan automático o editar estos valores manualmente.</p><div className="settings-grid"><label>Calorías<input type="number" value={form.macroGoals.calories} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,calories:e.target.value}})}/></label><label>Proteína (g)<input type="number" value={form.macroGoals.protein} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,protein:e.target.value}})}/></label><label>Carbohidratos (g)<input type="number" value={form.macroGoals.carbs} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,carbs:e.target.value}})}/></label><label>Grasas (g)<input type="number" value={form.macroGoals.fats} onChange={e=>setForm({...form,macroGoals:{...form.macroGoals,fats:e.target.value}})}/></label><label>Agua (L)<input type="number" step="0.1" value={form.waterGoalLiters} onChange={e=>set('waterGoalLiters',e.target.value)}/></label><label>Botella (L)<input type="number" step="0.05" value={form.bottleSizeLiters} onChange={e=>set('bottleSizeLiters',e.target.value)}/></label><label>Gym por semana<input type="number" value={form.weeklyGymGoal} onChange={e=>set('weeklyGymGoal',e.target.value)}/></label><label>Pasos por día<input type="number" step="500" value={form.dailyStepGoal} onChange={e=>set('dailyStepGoal',e.target.value)}/></label><label>Sueño objetivo (h)<input type="number" step="0.25" value={form.sleepGoalHours} onChange={e=>set('sleepGoalHours',e.target.value)}/></label></div></Card><ErrorBox message={error}/><button className="btn primary profile-save"><Save size={18}/>{saved?'Guardado':'Guardar cambios'}</button></form>
 <Card className="account-card"><SectionTitle title="Cuenta" action={<ShieldCheck size={18}/>}/><p className="muted">Tus datos sensibles permanecen privados salvo que vos decidas compartirlos.</p><button className="btn danger-outline" onClick={()=>{logout();nav('/auth')}}><LogOut size={18}/> Cerrar sesión</button></Card>
 </div>;
}
