import { useEffect, useState } from 'react';
import { CalendarDays, Dumbbell, Flame, Footprints, Medal, Moon, Plus, Ruler, Scale, TrendingUp } from 'lucide-react';
import { endpoints } from '../services/api.js';
import { Card, ErrorBox, Loading, Modal, Pill, Progress, SectionTitle, StatMini } from '../components/Ui.jsx';
import Sparkline from '../components/Sparkline.jsx';
import { n, shortDate } from '../utils/format.js';

export default function ProgressPage(){
 const [period,setPeriod]=useState('week'),[summary,setSummary]=useState(null),[weights,setWeights]=useState([]),[measurements,setMeasurements]=useState([]),[calendar,setCalendar]=useState([]),[streaks,setStreaks]=useState(null),[game,setGame]=useState(null),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[error,setError]=useState('');
 const load=async()=>{try{setLoading(true);const [s,w,m,c,st,g]=await Promise.all([endpoints.statsSummary(period),endpoints.weights(),endpoints.measurements(),endpoints.calendar(),endpoints.streaks(),endpoints.gamification()]);setSummary(s);setWeights(w);setMeasurements(m);setCalendar(c);setStreaks(st);setGame(g);}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[period]); if(loading)return <Loading/>;
 return <div className="page"><div className="page-heading"><div><span className="eyebrow">Progreso</span><h1>Tus números cuentan la historia.</h1></div><select className="period-select" value={period} onChange={e=>setPeriod(e.target.value)}><option value="week">Semana</option><option value="month">Mes</option></select></div><ErrorBox message={error}/>
 <div className="stat-grid"><StatMini icon={TrendingUp} tone="purple" label="Score promedio" value={`${n(summary?.averages?.score)} / 100`}/><StatMini icon={Footprints} tone="green" label="Pasos promedio" value={n(summary?.averages?.steps)}/><StatMini icon={Moon} tone="yellow" label="Sueño promedio" value={`${n(summary?.averages?.sleepHours,1)} h`}/><StatMini icon={Scale} tone="purple" label="Cambio de peso" value={summary?.weight?`${summary.weight.changeLb>=0?'+':''}${n(summary.weight.changeLb,2)} lb`:'—'}/></div>
 <div className="progress-action-grid"><button onClick={()=>setModal('activity')}><Footprints/><div><strong>Registrar pasos</strong><small>Sumá actividad y km</small></div><Plus size={16}/></button><button onClick={()=>setModal('sleep')}><Moon/><div><strong>Registrar sueño</strong><small>Horas de recuperación</small></div><Plus size={16}/></button></div>
 <Card><SectionTitle title="Peso" action={<div className="title-actions"><Pill tone="neutral">{weights.length?`${n(weights.at(-1).weightLb,1)} lb`:'Sin datos'}</Pill><button className="mini-add" onClick={()=>setModal('weight')}><Plus size={15}/></button></div>}/><Sparkline values={weights.slice(-30).map(x=>x.weightLb)}/>{weights.length>1&&<div className="chart-foot"><span>{shortDate(weights[Math.max(0,weights.length-30)].loggedAt)}</span><span>{shortDate(weights.at(-1).loggedAt)}</span></div>}</Card>
 <Card><SectionTitle title="Actividad y recuperación"/><div className="metric-bars"><Metric label="Pasos promedio" value={`${n(summary?.averages?.steps)} pasos`} percent={Math.min(100,(summary?.averages?.steps||0)/100)} tone="green"/><Metric label="Distancia promedio" value={`${n(summary?.averages?.distanceKm,2)} km`} percent={Math.min(100,(summary?.averages?.distanceKm||0)*10)} tone="purple"/><Metric label="Sueño promedio" value={`${n(summary?.averages?.sleepHours,1)} h`} percent={Math.min(100,(summary?.averages?.sleepHours||0)/8*100)} tone="yellow"/></div><div className="activity-totals"><span><Footprints size={16}/><strong>{n(summary?.totals?.steps)} pasos</strong><small>{n(summary?.totals?.distanceKm,2)} km totales</small></span><span><Moon size={16}/><strong>{n(summary?.totals?.sleepHours,1)} h</strong><small>{n(summary?.completions?.sleepGoalDays)} días en meta</small></span></div></Card>
 <Card><SectionTitle title="Promedios"/><div className="metric-bars"><Metric label="Calorías" value={`${n(summary?.averages?.calories)} kcal`} percent={Math.min(100,summary?.averages?.score||0)}/><Metric label="Proteína" value={`${n(summary?.averages?.protein,1)} g`} percent={Math.min(100,summary?.averages?.score||0)} tone="green"/><Metric label="Agua" value={`${n(summary?.averages?.waterLiters,1)} L`} percent={Math.min(100,summary?.averages?.score||0)} tone="blue"/><Metric label="Gym" value={`${n(summary?.completions?.gymDays)} días`} percent={Math.min(100,(summary?.completions?.gymDays||0)*25)} tone="yellow"/></div></Card>
 <Card><SectionTitle title="Rachas"/><div className="streak-grid">{Object.entries(streaks||{}).map(([key,val])=><div key={key}><Flame size={20}/><strong>{typeof val==='number'?val:0}</strong><span>{streakLabel(key)}</span></div>)}</div></Card>
 <Card><SectionTitle title="Calendario" action={<CalendarDays size={18}/>}/><CalendarGrid rows={calendar}/></Card>
 <Card><SectionTitle title="Insignias" action={<Medal size={18}/>}/><div className="badge-grid">{game?.achievements?.map(a=><div className={a.earned?'badge earned':'badge'} key={a.key}><span>{a.icon}</span><div><strong>{a.name}</strong><small>{a.earned?'Desbloqueada':a.description}</small></div></div>)}</div></Card>
 <Card><SectionTitle title="Medidas corporales" action={<button className="mini-add" onClick={()=>setModal('measure')}><Plus size={15}/></button>}/>{measurements.length>0?<><div className="measurement-grid">{Object.entries(measurements.at(-1)).filter(([k,v])=>k.endsWith('Cm')&&v!=null).map(([k,v])=><div key={k}><span>{measureLabel(k)}</span><strong>{n(v,1)} cm</strong></div>)}</div><p className="fineprint measurement-date">Último registro: {shortDate(measurements.at(-1).loggedAt)}</p></>:<div className="measurement-empty"><Ruler size={24}/><span>Agregá tus primeras medidas para comparar cambios.</span></div>}</Card>
 <Modal open={modal==='weight'} title="Registrar peso" onClose={()=>setModal(null)}><WeightForm onDone={()=>{setModal(null);load()}}/></Modal>
 <Modal open={modal==='activity'} title="Registrar actividad" onClose={()=>setModal(null)}><ActivityForm onDone={()=>{setModal(null);load();window.dispatchEvent(new Event('fitcore:refresh'))}}/></Modal>
 <Modal open={modal==='sleep'} title="Registrar sueño" onClose={()=>setModal(null)}><SleepForm onDone={()=>{setModal(null);load();window.dispatchEvent(new Event('fitcore:refresh'))}}/></Modal>
 <Modal open={modal==='measure'} title="Registrar medidas" onClose={()=>setModal(null)} wide><MeasurementForm onDone={()=>{setModal(null);load()}}/></Modal>
 </div>;
}
function Metric({label,value,percent,tone='purple'}){return <div><div className="metric-head"><span>{label}</span><strong>{value}</strong></div><Progress value={percent} tone={tone}/></div>}
function CalendarGrid({rows}){const map=new Map(rows.map(r=>[new Date(r.date).getDate(),r]));const now=new Date();const days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const startDay=new Date(now.getFullYear(),now.getMonth(),1).getDay();return <><div className="calendar-weekdays">{['D','L','M','X','J','V','S'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{Array.from({length:startDay},(_,i)=><div key={`e${i}`} className="calendar-day spacer"/>)}{Array.from({length:days},(_,i)=>i+1).map(day=>{const r=map.get(day);const tone=!r?'none':r.score>=80?'good':r.score>=60?'mid':'low';return <div key={day} className={`calendar-day ${tone}`} title={r?`Score ${r.score} · ${n(r.steps)} pasos · ${n(r.sleepHours,1)} h sueño`:'Sin registro'}><span>{day}</span>{r&&<i/>}</div>})}</div></>}
function WeightForm({onDone}){const [weight,setWeight]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[error,setError]=useState('');return <form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await endpoints.addWeight({weightLb:Number(weight),loggedAt:new Date(`${date}T12:00:00`).toISOString()});onDone()}catch(err){setError(err.message)}}}><label>Peso (lb)<input autoFocus type="number" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} required/></label><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><ErrorBox message={error}/><button className="btn primary">Guardar peso</button></form>}
function ActivityForm({onDone}){const [steps,setSteps]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[error,setError]=useState('');return <form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await endpoints.addActivity({steps:Number(steps),loggedAt:new Date(`${date}T18:00:00`).toISOString()});onDone()}catch(err){setError(err.message)}}}><label>Pasos<input autoFocus type="number" min="0" value={steps} onChange={e=>setSteps(e.target.value)} placeholder="10000" required/></label><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><p className="fineprint">La distancia se estima automáticamente a partir de tus pasos y altura.</p><ErrorBox message={error}/><button className="btn primary">Guardar actividad</button></form>}
function SleepForm({onDone}){const [hours,setHours]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[error,setError]=useState('');return <form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await endpoints.addSleep({hours:Number(hours),loggedAt:new Date(`${date}T08:00:00`).toISOString()});onDone()}catch(err){setError(err.message)}}}><label>Horas dormidas<input autoFocus type="number" min="0" max="24" step="0.25" value={hours} onChange={e=>setHours(e.target.value)} placeholder="7.5" required/></label><label>Día al que corresponde<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><ErrorBox message={error}/><button className="btn primary">Guardar sueño</button></form>}
function MeasurementForm({onDone}){const [form,setForm]=useState({armCm:'',chestCm:'',waistCm:'',hipsCm:'',thighCm:'',calfCm:'',notes:''}),[error,setError]=useState('');const fields=[['armCm','Brazo'],['chestCm','Pecho'],['waistCm','Cintura'],['hipsCm','Cadera'],['thighCm','Muslo'],['calfCm','Pantorrilla']];return <form className="form-stack" onSubmit={async e=>{e.preventDefault();try{const payload={notes:form.notes};fields.forEach(([k])=>{if(form[k]!=='' )payload[k]=Number(form[k])});await endpoints.addMeasurement(payload);onDone()}catch(err){setError(err.message)}}}><div className="settings-grid">{fields.map(([k,label])=><label key={k}>{label} (cm)<input type="number" step="0.1" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label>Nota opcional<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Medición en ayunas"/></label><ErrorBox message={error}/><button className="btn primary">Guardar medidas</button></form>}
function streakLabel(k){return ({mealLoggingDays:'comidas',proteinGoalDays:'proteína',waterGoalDays:'agua',score80Days:'score 80+',stepGoalDays:'pasos',sleepGoalDays:'sueño',gymGoalWeeks:'semanas gym'})[k]||k}
function measureLabel(k){return ({armCm:'Brazo',chestCm:'Pecho',waistCm:'Cintura',hipsCm:'Cadera',thighCm:'Muslo',calfCm:'Pantorrilla'})[k]||k}
