import { useEffect, useState } from 'react';
import { BellRing, Eye, LockKeyhole, MoonStar } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { endpoints } from '../services/api.js';
import { Card, ErrorBox, Loading, SectionTitle } from '../components/Ui.jsx';

const privacyLabels={weight:'Peso',measurements:'Medidas corporales',macros:'Macros',meals:'Comidas',score:'Score',gym:'Gym',streaks:'Rachas'};
export default function SettingsPage(){const {user,refreshUser}=useAuth();const [privacy,setPrivacy]=useState(user.privacy||{}),[prefs,setPrefs]=useState(null),[error,setError]=useState('');useEffect(()=>{endpoints.reminderPrefs().then(setPrefs).catch(e=>setError(e.message))},[]);if(!prefs)return <Loading/>;const savePrivacy=async()=>{try{await endpoints.updateMe({privacy});await refreshUser()}catch(e){setError(e.message)}};const savePrefs=async()=>{try{setPrefs(await endpoints.updateReminderPrefs(prefs))}catch(e){setError(e.message)}};return <div className="page"><div className="page-heading"><div><span className="eyebrow">Configuración</span><h1>FitCore a tu manera.</h1></div></div><ErrorBox message={error}/>
<Card><SectionTitle title="Privacidad" action={<LockKeyhole size={18}/>}/><p className="muted">Elegí qué métricas pueden ver tus amigos.</p><div className="settings-list">{Object.entries(privacyLabels).map(([key,label])=><div key={key}><div><Eye size={18}/><span>{label}</span></div><select value={privacy[key]||'private'} onChange={e=>setPrivacy({...privacy,[key]:e.target.value})}><option value="private">Privado</option><option value="friends">Amigos</option></select></div>)}</div><button className="btn secondary" onClick={savePrivacy}>Guardar privacidad</button></Card>
<Card><SectionTitle title="Recordatorios" action={<BellRing size={18}/>}/><Toggle label="Activar recordatorios" value={prefs.enabled} onChange={v=>setPrefs({...prefs,enabled:v})}/><Toggle label="Comidas" value={prefs.mealReminder} onChange={v=>setPrefs({...prefs,mealReminder:v})}/><Toggle label="Agua" value={prefs.waterReminder} onChange={v=>setPrefs({...prefs,waterReminder:v})}/><Toggle label="Proteína" value={prefs.proteinReminder} onChange={v=>setPrefs({...prefs,proteinReminder:v})}/><Toggle label="Gym" value={prefs.gymReminder} onChange={v=>setPrefs({...prefs,gymReminder:v})}/><Toggle label="Rachas" value={prefs.streakReminder} onChange={v=>setPrefs({...prefs,streakReminder:v})}/><div className="quiet-hours"><div><MoonStar size={18}/><span>Horas silenciosas</span></div><input type="time" value={prefs.quietHours?.start||'22:00'} onChange={e=>setPrefs({...prefs,quietHours:{...prefs.quietHours,start:e.target.value,enabled:true}})}/><span>—</span><input type="time" value={prefs.quietHours?.end||'07:00'} onChange={e=>setPrefs({...prefs,quietHours:{...prefs.quietHours,end:e.target.value,enabled:true}})}/></div><button className="btn secondary" onClick={savePrefs}>Guardar recordatorios</button></Card></div>}
function Toggle({label,value,onChange}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/><i/></label>}
