import { useEffect, useState } from 'react';
import { Check, ChevronRight, Crown, Plus, Search, Swords, Trophy, UserPlus, Users, X } from 'lucide-react';
import { endpoints } from '../services/api.js';
import { Card, Empty, ErrorBox, Loading, Modal, Pill, Progress, SectionTitle } from '../components/Ui.jsx';
import { n } from '../utils/format.js';
import { useAuth } from '../context/AuthContext.jsx';
import { avatarUrl } from '../utils/avatar.js';

export default function SocialPage(){
 const { user } = useAuth();
 const [ranking,setRanking]=useState([]),[friends,setFriends]=useState([]),[requests,setRequests]=useState([]),[challenges,setChallenges]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[results,setResults]=useState([]),[modal,setModal]=useState(null),[selectedFriend,setSelectedFriend]=useState(null);
 const load=async()=>{try{setError('');const [r,f,req,c]=await Promise.all([endpoints.ranking(),endpoints.friends(),endpoints.requests(),endpoints.challenges()]);setRanking(r);setFriends(f);setRequests(req);setChallenges(c);}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const search=async(e)=>{const value=e.target.value;setQ(value);if(value.length>=2)try{setResults(await endpoints.searchUsers(value))}catch{}else setResults([])};
 const openFriend=async(id)=>{try{setSelectedFriend(await endpoints.friendOverview(id));setModal('friend')}catch(e){setError(e.message)}};
 if(loading)return <Loading/>;
 return <div className="page"><div className="page-heading"><div><span className="eyebrow">Social</span><h1>Progresar acompañado pega distinto.</h1></div><button className="btn primary compact" onClick={()=>setModal('challenge')}><Plus size={18}/> Reto</button></div><ErrorBox message={error}/>
 <Card className="ranking-card"><SectionTitle title="Ranking semanal" action={<Trophy size={19}/>}/>{ranking.length?<div className="ranking-list">{ranking.slice(0,7).map(r=><div key={r.id} className={r.rank===1?'rank first':'rank'}><span className="rank-pos">{r.rank===1?<Crown size={19}/>:r.rank}</span><div className="avatar-small image"><img src={avatarUrl(r.avatarId)} alt=""/></div><div className="rank-user"><strong>{r.name}</strong><span>@{r.username} · {r.trackedDays} días</span></div><b>{r.weeklyScore}</b></div>)}</div>:<Empty icon={Trophy} title="Todavía no hay ranking" text="Agregá amigos y completen algunos días para competir."/>}</Card>
 <div className="social-grid"><Card><SectionTitle title="Amigos" action={<Users size={18}/>}/><div className="search-box"><Search size={17}/><input value={q} onChange={search} placeholder="Buscar @usuario"/></div>{results.length>0&&<div className="search-results">{results.map(u=><div key={u.id}><div className="avatar-small image"><img src={avatarUrl(u.avatarId)} alt=""/></div><div><strong>{u.name}</strong><span>@{u.username}</span></div><button className="icon-btn" onClick={async()=>{try{await endpoints.sendRequest(u.username);setResults([]);setQ('')}catch(e){setError(e.message)}}}><UserPlus size={17}/></button></div>)}</div>}<div className="compact-list friends-list">{friends.map(f=><button key={f.id} onClick={()=>openFriend(f.id)}><div className="friend-line"><div className="avatar-small image"><img src={avatarUrl(f.avatarId)} alt=""/></div><div><strong>{f.name}</strong><span>@{f.username} · Nivel {f.level}</span></div></div><ChevronRight size={17}/></button>)}</div>{friends.length===0&&<p className="muted">Buscá a tus amigos por username.</p>}</Card>
 <Card><SectionTitle title="Solicitudes"/><div className="request-list">{requests.map(r=><div key={r._id}><div className="avatar-small image"><img src={avatarUrl(r.requester?.avatarId)} alt=""/></div><div><strong>{r.requester?.name}</strong><span>@{r.requester?.username}</span></div><button className="icon-btn success" onClick={async()=>{await endpoints.respondRequest(r._id,'accepted');load()}}><Check size={17}/></button><button className="icon-btn danger" onClick={async()=>{await endpoints.respondRequest(r._id,'rejected');load()}}><X size={17}/></button></div>)}{requests.length===0&&<p className="muted">No tenés solicitudes pendientes.</p>}</div></Card></div>
 <SectionTitle title="Retos" action={<Swords size={19}/>}/><div className="challenge-list">{challenges.length?challenges.map(c=><ChallengeCard key={c._id} challenge={c} userId={user?._id} onUpdate={load}/>):<Empty icon={Swords} title="Sin retos todavía" text="Creá un reto con tus amigos y sumá XP."/>}</div>
 <Modal open={modal==='challenge'} title="Crear reto" onClose={()=>setModal(null)}><ChallengeForm friends={friends} onDone={()=>{setModal(null);load()}}/></Modal>
 <Modal open={modal==='friend'} title={selectedFriend?.user?.name||'Amigo'} onClose={()=>{setModal(null);setSelectedFriend(null)}}><FriendOverview data={selectedFriend}/></Modal>
 </div>;
}
function ChallengeCard({challenge,userId,onUpdate}){const me=challenge.participants?.find(p=>{const id=typeof p.user==='object'?p.user?._id:p.user;return String(id)===String(userId)})||challenge.participants?.[0];const progress=Number(me?.progress||0);const percent=Math.min(100,Math.round((progress/challenge.target)*100));const [value,setValue]=useState(progress);return <Card className="challenge-card expanded"><div className="challenge-top"><div><Pill tone={challenge.status==='active'?'green':'neutral'}>{challenge.status}</Pill><h3>{challenge.name}</h3><span>{challenge.type} · objetivo {challenge.target}</span></div><div className="challenge-people">{challenge.participants?.slice(0,4).map((p,i)=><span key={i} title={p.user?.name}><img src={avatarUrl(p.user?.avatarId)} alt=""/></span>)}</div></div><Progress value={percent} tone="green"/><div className="challenge-progress-row"><span>{progress} / {challenge.target}</span>{challenge.status==='active'&&<div><input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)}/><button className="btn secondary compact" onClick={async()=>{await endpoints.challengeProgress(challenge._id,Number(value));onUpdate()}}>Actualizar</button></div>}</div></Card>}
function ChallengeForm({friends,onDone}){const [form,setForm]=useState({name:'',type:'hydration',target:7,startDate:new Date().toISOString().slice(0,10),endDate:new Date(Date.now()+7*86400000).toISOString().slice(0,10),usernames:[]}),[error,setError]=useState('');const toggle=u=>setForm(v=>({...v,usernames:v.usernames.includes(u)?v.usernames.filter(x=>x!==u):[...v.usernames,u]}));return <form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await endpoints.createChallenge({...form,target:Number(form.target)});onDone()}catch(err){setError(err.message)}}}><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Hydration Week" required/></label><div className="form-row"><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="hydration">Agua</option><option value="protein">Proteína</option><option value="gym">Gym</option><option value="score">Score</option><option value="consistency">Consistencia</option></select></label><label>Objetivo<input type="number" min="1" value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/></label></div><div className="form-row"><label>Inicio<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Final<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div><label>Invitar amigos</label><div className="friend-picker">{friends.map(f=><button type="button" key={f.id} className={form.usernames.includes(f.username)?'selected':''} onClick={()=>toggle(f.username)}>@{f.username}</button>)}</div><ErrorBox message={error}/><button className="btn primary">Crear reto</button></form>}
function FriendOverview({data}){if(!data)return null;const v=data.visible||{};return <div className="friend-overview"><div className="friend-profile"><div className="profile-avatar avatar-image"><img src={avatarUrl(data.user?.avatarId)} alt=""/></div><div><h3>{data.user?.name}</h3><span>@{data.user?.username} · Nivel {data.user?.level}</span></div></div><div className="friend-metrics">{v.score!==undefined&&<Metric label="Score semanal" value={v.score}/>} {v.gymThisWeek!==undefined&&<Metric label="Gym esta semana" value={v.gymThisWeek}/>} {v.latestWeight&&<Metric label="Peso" value={`${n(v.latestWeight.weightKg,1)} kg`}/>} {v.macros?.nutrition&&<Metric label="Proteína" value={`${n(v.macros.nutrition.protein,1)} g`}/>} {v.stepsThisWeek!==undefined&&<Metric label="Pasos esta semana" value={n(v.stepsThisWeek)}/>} {v.distanceKmThisWeek!==undefined&&<Metric label="Km esta semana" value={`${n(v.distanceKmThisWeek,1)} km`}/>} {v.avgSleepHours!==undefined&&<Metric label="Sueño promedio" value={`${n(v.avgSleepHours,1)} h`}/>}</div>{v.recentMeals?.length>0&&<div><span className="eyebrow">Comidas recientes</span><div className="compact-list">{v.recentMeals.map((m,i)=><div key={i}><div><strong>{m.title||m.type}</strong><span>{new Date(m.loggedAt).toLocaleDateString('es-SV')}</span></div></div>)}</div></div>}</div>}
function Metric({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
